version: '3'

services:
    bitcoind:
        build: .
        volumes:
            - "bitcoin-data:/data"
        networks:
            - bitcoin
        stdin_open: true
        tty: true
        ports:
            - "8332:8332"
            - "8333:8333"
            - "18332:18332"
            - "18333:18333"
            - "18443:18443"
            - "18444:18444"
            

volumes:
    bitcoin-data:

networks:
    bitcoin:
